(function() {var implementors = {};
implementors["bincode"] = [{text:"impl&lt;'storage&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">IoRead</a> for <a class=\"struct\" href=\"bincode/read_types/struct.SliceReader.html\" title=\"struct bincode::read_types::SliceReader\">SliceReader</a>&lt;'storage&gt;",synthetic:false,types:["bincode::de::read::SliceReader"]},{text:"impl&lt;R:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">IoRead</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">IoRead</a> for <a class=\"struct\" href=\"bincode/read_types/struct.IoReadReader.html\" title=\"struct bincode::read_types::IoReadReader\">IoReadReader</a>&lt;R&gt;",synthetic:false,types:["bincode::de::read::IoReadReader"]},];
implementors["either"] = [{text:"impl&lt;L, R&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"enum\" href=\"either/enum.Either.html\" title=\"enum either::Either\">Either</a>&lt;L, R&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;L: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;R: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a>,&nbsp;</span>",synthetic:false,types:["either::Either"]},];
implementors["inflate"] = [{text:"impl&lt;R:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.BufRead.html\" title=\"trait std::io::BufRead\">BufRead</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"inflate/struct.DeflateDecoderBuf.html\" title=\"struct inflate::DeflateDecoderBuf\">DeflateDecoderBuf</a>&lt;R&gt;",synthetic:false,types:["inflate::reader::DeflateDecoderBuf"]},{text:"impl&lt;R:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"inflate/struct.DeflateDecoder.html\" title=\"struct inflate::DeflateDecoder\">DeflateDecoder</a>&lt;R&gt;",synthetic:false,types:["inflate::reader::DeflateDecoder"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
