language: rust
before_script:
  - echo "yes" | sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main universe restricted multiverse"
  - sudo apt-get update -qq
  - sudo apt-get -qq install libsdl2-dev
rust:
  - 1.8.0
