environment:
  TARGET: x86_64-pc-windows-gnu
  RUST_VERSION: 1.73.0
  BITS: 64
install:
  - SET PATH=C:\msys64\mingw%BITS%\bin;C:\msys64\usr\bin;%PATH%
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - echo %PATH%
  - gcc --version
  - rustc -V
  - cargo -V

build_script:
    - cargo build --no-default-features --features include_glutin --verbose

test_script:
    - cargo test --no-default-features --features include_glutin --verbose

