[package]
name = "rpsrtsrs"
version = "0.1.0"
authors = ["Raphael Nestler <raphael.nestler@gmail.com>"]

[dependencies]
piston = "*"
piston2d-graphics = "*"
pistoncore-glutin_window = "*"
piston2d-opengl_graphics = "*"
