[package]
name = "rpsrtsrs"
version = "0.1.0"
authors = ["Raphael Nestler <raphael.nestler@gmail.com>"]

[dependencies]
rand = "0.3"
piston = "0.25"
piston2d-graphics = "0.17"
piston2d-opengl_graphics = "0.33"
bincode = "0.6"
rustc-serialize = "0.3"
docopt = "0.7"

[dependencies.pistoncore-sdl2_window]
version = "0.35"
optional = true

[dependencies.pistoncore-glfw_window]
version = "0.25"
optional = true

[dependencies.pistoncore-glutin_window]
version = "0.30"
optional = true

[features]
default = ["include_sdl2"]
include_sdl2 = ["pistoncore-sdl2_window"]
include_glfw = ["pistoncore-glfw_window"]
include_glutin = ["pistoncore-glutin_window"]

