[package]
name = "rpsrtsrs"
version = "0.1.0"
authors = ["Raphael Nestler <raphael.nestler@gmail.com>"]

[dependencies]
rand = "*"
piston = "0.4"
piston2d-graphics = "0.4"
pistoncore-glutin_window = "0.6"
piston2d-opengl_graphics = "0.6"
